export const Permissions = {
    // Applicant Management
    READ_APPLICANT: 'READ_APPLICANT',
    APPROVE_APPLICANT: 'APPROVE_APPLICANT',
    DENY_APPLICANT: 'DENY_APPLICANT',
    UPDATE_APPLICANT: 'UPDATE_APPLICANT',
    CHANGE_APPLICANT_RATING: 'CHANGE_APPLICANT_RATING',
    CHANGE_APPLICANT_STAGE: 'CHANGE_APPLICANT_STAGE',

    // User Management
    READ_ALL_USERS: 'READ_ALL_USERS',
    READ_USER: 'READ_USER',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_MY_PROFILE: 'UPDATE_MY_PROFILE',
    DELETE_USER: 'DELETE_USER',

    // Organization Management
    READ_ORG: 'READ_ORG',
    CREATE_ORG: 'CREATE_ORG',
    UPDATE_ORG: 'UPDATE_ORG',
    DELETE_ORG: 'DELETE_ORG',

    // Job Listing Management
    READ_JOB_LISTING: 'READ_JOB_LISTING',
    CREATE_JOB_LISTING: 'CREATE_JOB_LISTING',
    UPDATE_JOB_LISTING: 'UPDATE_JOB_LISTING',
    DELETE_JOB_LISTING: 'DELETE_JOB_LISTING',
    CHANGE_JOB_LISTING_STATUS: 'CHANGE_JOB_LISTING_STATUS',

    // Billing
    READ_BILLING: 'READ_BILLING',
} as const;

